# Generated by Django 4.1.7 on 2023-06-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trutests", "0005_alter_animal_fecha_alter_animal_hora_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Potrero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("animales", models.ManyToManyField(to="trutests.animal")),
            ],
        ),
    ]
