# Generated by Django 4.1.7 on 2023-06-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("potreros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="potrero",
            name="size",
            field=models.IntegerField(default=2235),
            preserve_default=False,
        ),
    ]
