# Generated by Django 4.1.7 on 2023-07-04 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("potreros", "0002_potrero_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Establishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="potrero",
            name="animales",
        ),
        migrations.RemoveField(
            model_name="potrero",
            name="size",
        ),
        migrations.AddField(
            model_name="potrero",
            name="establishment",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="potreros.establishment",
            ),
            preserve_default=False,
        ),
    ]
