# Generated by Django 4.1.7 on 2023-07-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("potreros", "0003_establishment_remove_potrero_animales_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potrero",
            name="establishment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="potreros",
                to="potreros.establishment",
            ),
        ),
    ]
