# Generated by Django 4.1.7 on 2023-05-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDE', models.CharField(max_length=100)),
                ('IDV', models.CharField(max_length=100)),
                ('FECHA', models.CharField(max_length=100)),
                ('HORA', models.CharField(max_length=100)),
                ('FECHA_DE_NAC', models.CharField(max_length=100)),
                ('RAZA', models.CharField(max_length=100)),
                ('UBICACION', models.CharField(max_length=100)),
                ('INSCRIPTA', models.CharField(max_length=100)),
                ('PESO', models.FloatField()),
                ('NOTA', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Animales',
            },
        ),
    ]
