# Generated by Django 4.1.7 on 2023-05-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trutests', '0003_rename_fecha_animal_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fecha_de_nac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
