# Generated by Django 4.1.7 on 2023-06-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trutests", "0005_alter_animal_fecha_alter_animal_hora_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="ide",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="idv",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
