# Generated by Django 4.1.7 on 2023-07-04 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("potreros", "0003_establishment_remove_potrero_animales_and_more"),
        ("trutests", "0006_alter_animal_ide_alter_animal_idv"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="potrero",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="potreros.potrero",
            ),
            preserve_default=False,
        ),
    ]
