# Generated by Django 4.1.7 on 2023-07-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("potreros", "0004_alter_potrero_establishment"),
        ("trutests", "0007_animal_potrero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="potrero",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animales",
                to="potreros.potrero",
            ),
        ),
    ]
