# Generated by Django 4.1.7 on 2023-05-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trutest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idv', models.CharField(blank=True, max_length=100)),
                ('peso', models.CharField(blank=True, max_length=100)),
                ('notas', models.CharField(blank=True, max_length=100)),
                ('ide', models.CharField(blank=True, max_length=100)),
                ('corral', models.CharField(blank=True, max_length=100)),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('vencimineto_lote', models.CharField(blank=True, max_length=100)),
                ('fechafinal_pr', models.CharField(blank=True, max_length=100)),
                ('fechafinal_ise', models.CharField(blank=True, max_length=100)),
                ('fecha', models.CharField(blank=True, max_length=100)),
                ('hora', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
