# Generated by Django 4.1.7 on 2023-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trutests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trutest',
            name='file',
            field=models.FileField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
