# Generated by Django 4.1.7 on 2023-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trutests', '0004_alter_animal_fecha_de_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fecha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='inscripta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
