# Generated by Django 4.1.7 on 2023-06-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("potreros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Establishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "potrero",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="potreros.potrero",
                    ),
                ),
            ],
        ),
    ]
