# Generated by Django 4.1.7 on 2023-06-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("establishment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishment",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
