# Generated by Django 4.1.7 on 2023-06-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("establishment", "0003_alter_establishment_potrero"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="location",
            field=models.CharField(default="localizacion", max_length=200),
            preserve_default=False,
        ),
    ]
